### ISSUE TITLE
Error about setup_cplex_inner_class_access()

### ISSUE THREAD

**Issue by cheng-yu-zhang** [LMSE/geneVa#1]
@VonAlphaBisZulu @kraj593 Hi, thanks for developing such a powerful tool. But I encounter a problem when I set up MoVE as you described in `README.md` step by step. At the last step,  `setup_cplex_inner_class_access()` always results in an empty struct, which would impact the `geneVa_demo_script_ec_core.m`.  And my system is windows11, matlab version is R2021b, the cplex is 12.7, the CellNetAnalyzer is the latest version 2022.1. Many thanks if you have any comment or solution.

**Comment by VonAlphaBisZulu** [comment]
This is usually a sign that CPLEX was not set up correctly. The CPLEX setup process is described in detail in the CellNetAnalyzer manual.

**Comment by cheng-yu-zhang** [comment]
Thanks a lot.
